"""
SQLAlchemy database models.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Enum as SQLEnum, UniqueConstraint, BigInteger
from sqlalchemy.sql import func
import enum

from db.database import Base


class OrderSide(str, enum.Enum):
    """Order side enum."""
    LONG = "LONG"
    SHORT = "SHORT"


class OrderStatus(str, enum.Enum):
    """Order status enum."""
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PositionStatus(str, enum.Enum):
    """Position status enum."""
    PENDING = "PENDING"  # Order placed, waiting for fill
    OPEN = "OPEN"        # Order filled, position active
    CLOSED = "CLOSED"    # Position exited


class LogLevel(str, enum.Enum):
    """Log level enum."""
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"


class Trade(Base):
    """
    Trade records table.
    
    Captures all metrics at entry time for full audit trail.
    Each row represents one trade from entry to exit.
    """
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)  # Trading day/time
    ticker = Column(String(10), nullable=False, index=True)
    side = Column(SQLEnum(OrderSide), nullable=False)
    
    # Entry details
    entry_price = Column(Float, nullable=False)
    entry_time = Column(DateTime, default=func.now(), nullable=False)
    shares = Column(Integer, nullable=False)
    
    # Exit details
    exit_price = Column(Float, nullable=True)
    exit_time = Column(DateTime, nullable=True)
    exit_reason = Column(String(50), nullable=True)  # STOP_LOSS, EOD, MANUAL, TARGET
    
    # P&L
    pnl = Column(Float, nullable=True)
    pnl_percent = Column(Float, nullable=True)
    
    # Order management
    status = Column(SQLEnum(PositionStatus), default=PositionStatus.PENDING, nullable=False)
    alpaca_order_id = Column(String(50), nullable=True, index=True)
    alpaca_exit_order_id = Column(String(50), nullable=True)
    
    # Risk levels (set at entry)
    stop_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    
    # ============ AUDIT FIELDS (snapshot at entry time) ============
    
    # Opening Range data
    or_open = Column(Float, nullable=True)
    or_high = Column(Float, nullable=True)
    or_low = Column(Float, nullable=True)
    or_close = Column(Float, nullable=True)
    or_volume = Column(Float, nullable=True)
    
    # Indicators at entry
    atr_14 = Column(Float, nullable=True)           # 14-day ATR
    avg_volume_14 = Column(Float, nullable=True)    # 14-day avg volume
    rvol = Column(Float, nullable=True)             # Relative volume (OR vol / avg vol)
    prev_close = Column(Float, nullable=True)       # Previous day close
    
    # Selection metadata
    rank = Column(Integer, nullable=True)           # RVOL rank (1-20)
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False)
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())


class Signal(Base):
    """
    Trading signals table.
    
    Generated by the scanner for each ORB candidate.
    Linked to Trade when order is filled.
    """
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    signal_date = Column(DateTime, nullable=False, index=True)  # Trading day
    timestamp = Column(DateTime, default=func.now(), nullable=False)
    ticker = Column(String(10), nullable=False, index=True)
    side = Column(SQLEnum(OrderSide), nullable=False)
    
    # Signal levels
    entry_price = Column(Float, nullable=False)   # OR high (long) or OR low (short)
    stop_price = Column(Float, nullable=True)     # Entry ± 10% ATR
    target_price = Column(Float, nullable=True)
    
    # Order tracking
    order_id = Column(String(50), nullable=True, index=True)
    status = Column(SQLEnum(OrderStatus), default=OrderStatus.PENDING, nullable=False)
    filled_price = Column(Float, nullable=True)
    filled_time = Column(DateTime, nullable=True)
    filled_shares = Column(Integer, nullable=True)
    rejection_reason = Column(String(255), nullable=True)
    
    # Link to trade (when filled)
    trade_id = Column(Integer, nullable=True, index=True)
    
    # ============ AUDIT FIELDS (snapshot at signal time) ============
    
    # Opening Range data
    or_open = Column(Float, nullable=True)
    or_high = Column(Float, nullable=True)
    or_low = Column(Float, nullable=True)
    or_close = Column(Float, nullable=True)
    or_volume = Column(Float, nullable=True)
    
    # Indicators
    atr_14 = Column(Float, nullable=True)
    avg_volume_14 = Column(Float, nullable=True)
    rvol = Column(Float, nullable=True)
    prev_close = Column(Float, nullable=True)
    
    # Selection metadata
    rank = Column(Integer, nullable=True)           # RVOL rank
    confidence = Column(Float, nullable=True)       # ML confidence if applicable
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False)


class SystemLog(Base):
    """System logs table."""
    __tablename__ = "logs"
    
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=func.now(), nullable=False, index=True)
    level = Column(SQLEnum(LogLevel), nullable=False, index=True)
    component = Column(String(50), nullable=False, index=True)
    message = Column(String(1000), nullable=False)
    extra_data = Column(String(500), nullable=True)


class DailyMetrics(Base):
    """Daily trading metrics table."""
    __tablename__ = "daily_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, nullable=False, unique=True, index=True)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)
    win_rate = Column(Float, default=0.0)
    starting_equity = Column(Float, nullable=False)
    ending_equity = Column(Float, nullable=False)


class DailyBar(Base):
    """
    Historical daily OHLCV bars from Polygon.
    Rolling 30-day window for ATR and avg volume calculation.
    """
    __tablename__ = "daily_bars"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    vwap = Column(Float, nullable=True)
    
    # Pre-computed metrics (updated nightly)
    atr_14 = Column(Float, nullable=True)
    avg_volume_14 = Column(Float, nullable=True)
    
    __table_args__ = (
        UniqueConstraint('symbol', 'date', name='uix_dailybar_symbol_date'),
    )


class Ticker(Base):
    """
    Stock universe from Polygon.
    Includes active and delisted tickers for survivorship-bias-free data.
    """
    __tablename__ = "tickers"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False, unique=True, index=True)
    name = Column(String(255), nullable=True)
    primary_exchange = Column(String(10), nullable=True)  # XNYS, XNAS
    type = Column(String(10), nullable=True)  # CS = Common Stock
    active = Column(Boolean, default=True, index=True)
    currency = Column(String(10), default="USD")
    cik = Column(String(20), nullable=True)
    delisted_utc = Column(DateTime, nullable=True)
    last_updated = Column(DateTime, default=func.now(), onupdate=func.now())
    
    # Pre-filter flags (updated during daily bar sync)
    meets_price_filter = Column(Boolean, default=False)  # price >= $5
    meets_volume_filter = Column(Boolean, default=False)  # avg_vol >= 1M
    meets_atr_filter = Column(Boolean, default=False)  # ATR >= $0.50
    
    # Float (shares outstanding) for low-float filtering
    float = Column(BigInteger, nullable=True)  # Shares outstanding (e.g., 5000000 = 5M shares)


class SimulatedTrade(Base):
    """
    Simulated/backtest trade records.
    
    Separate from Trade table to avoid confusion with live trades.
    These are "what if" results from the historical scanner.
    """
    __tablename__ = "simulated_trades"
    
    id = Column(Integer, primary_key=True, index=True)
    backtest_run_id = Column(Integer, nullable=True, index=True)  # NULL = default/production run
    trade_date = Column(DateTime, nullable=False, index=True)  # Trading day
    ticker = Column(String(10), nullable=False, index=True)
    side = Column(SQLEnum(OrderSide), nullable=False)
    
    # Ranking
    rvol_rank = Column(Integer, nullable=False)  # 1-20
    rvol = Column(Float, nullable=False)
    
    # Opening Range data
    or_open = Column(Float, nullable=False)
    or_high = Column(Float, nullable=False)
    or_low = Column(Float, nullable=False)
    or_close = Column(Float, nullable=False)
    or_volume = Column(Float, nullable=False)
    
    # Entry/Exit
    entry_price = Column(Float, nullable=False)  # OR high (long) or OR low (short)
    stop_price = Column(Float, nullable=False)   # Entry ± 10% ATR
    exit_price = Column(Float, nullable=True)    # Actual exit price
    exit_reason = Column(String(20), nullable=True)  # STOPPED, EOD, NO_ENTRY
    entry_time = Column(String(10), nullable=True)   # HH:MM format
    exit_time = Column(String(10), nullable=True)    # HH:MM format
    
    # P&L (null if NO_ENTRY)
    pnl_pct = Column(Float, nullable=True)
    day_change_pct = Column(Float, nullable=True)  # Stock's % change that day
    
    # Position sizing (fixed 2x leverage)
    stop_distance_pct = Column(Float, nullable=True)  # Stop distance as % of entry
    leverage = Column(Float, nullable=True)           # Effective leverage (2.0)
    dollar_pnl = Column(Float, nullable=True)         # Dollar P&L at leverage
    base_dollar_pnl = Column(Float, nullable=True)    # Dollar P&L at 1x leverage
    
    # Metrics at time of scan
    atr_14 = Column(Float, nullable=True)
    avg_volume_14 = Column(Float, nullable=True)
    prev_close = Column(Float, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False)
    
    __table_args__ = (
        UniqueConstraint('backtest_run_id', 'trade_date', 'ticker', name='uix_simtrade_run_date_ticker'),
    )


class OpeningRange(Base):
    """
    Opening range data (first 5-min bar) captured each trading day.
    Stores candidates that pass initial filters for review/debugging.
    """
    __tablename__ = "opening_ranges"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    
    # Opening range bar data
    or_open = Column(Float, nullable=False)
    or_high = Column(Float, nullable=False)
    or_low = Column(Float, nullable=False)
    or_close = Column(Float, nullable=False)
    or_volume = Column(Float, nullable=False)
    
    # Direction: 1 = bullish (long), -1 = bearish (short), 0 = doji (skip)
    direction = Column(Integer, nullable=False)
    
    # Computed metrics
    rvol = Column(Float, nullable=True)  # Relative volume
    atr = Column(Float, nullable=True)   # 14-day ATR at time of scan
    avg_volume = Column(Float, nullable=True)  # 14-day avg volume
    
    # Filter results
    passed_filters = Column(Boolean, default=False)  # Met all criteria
    rank = Column(Integer, nullable=True)  # Rank by RVOL (1-20 = top 20)
    
    # Entry levels
    entry_price = Column(Float, nullable=True)  # OR high (long) or OR low (short)
    stop_price = Column(Float, nullable=True)   # 10% ATR from entry
    
    # Outcome tracking
    signal_generated = Column(Boolean, default=False)
    order_placed = Column(Boolean, default=False)
    
    __table_args__ = (
        {"sqlite_autoincrement": True},
    )


class ScannerCache(Base):
    """
    Cache metadata for scanner results.
    
    Tracks which dates have been scanned to avoid re-fetching
    data for holidays/no-trading days.
    """
    __tablename__ = "scanner_cache"
    
    id = Column(Integer, primary_key=True, index=True)
    scan_date = Column(DateTime, nullable=False, unique=True, index=True)  # The date scanned
    
    # Result status
    status = Column(String(50), nullable=False)  # 'success', 'no_data', 'holiday', 'error'
    candidates_count = Column(Integer, default=0)  # Number of candidates found
    trades_entered = Column(Integer, default=0)    # Number that triggered entry
    
    # Summary stats (for quick display without loading all trades)
    total_pnl_pct = Column(Float, nullable=True)
    winners = Column(Integer, default=0)
    losers = Column(Integer, default=0)
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False)
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), nullable=False)


# ============ HISTORICAL BACKTEST TABLES ============

class DailyMetricsHistorical(Base):
    """
    Pre-computed daily metrics for all symbols across all historical dates.
    
    Used by bulk backtest to avoid recomputing ATR/avg_vol for each date.
    Computed from parquet files in data/processed/daily/
    """
    __tablename__ = "daily_metrics_historical"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    
    # OHLCV for the day
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    
    # Pre-computed metrics (14-day lookback)
    atr_14 = Column(Float, nullable=True)
    avg_volume_14 = Column(Float, nullable=True)
    prev_close = Column(Float, nullable=True)
    
    # Filter flags (computed at insert time)
    meets_price_filter = Column(Boolean, default=False)   # close >= $5
    meets_volume_filter = Column(Boolean, default=False)  # avg_volume_14 >= 1M
    meets_atr_filter = Column(Boolean, default=False)     # atr_14 >= $0.50
    passes_all_filters = Column(Boolean, default=False)   # All 3 filters
    
    __table_args__ = (
        UniqueConstraint('symbol', 'date', name='uix_dailymetrics_symbol_date'),
    )


class BacktestRun(Base):
    """
    Track different backtest configurations/runs.
    
    Allows comparing different strategy variants (e.g., top 10 vs top 20).
    """
    __tablename__ = "backtest_runs"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)  # e.g., "ORB Top20 2x Leverage"
    description = Column(String(500), nullable=True)
    
    # Date range
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    
    # Strategy parameters (stored as JSON-like string)
    top_n = Column(Integer, default=20)           # Number of candidates to trade
    capital = Column(Float, default=1000.0)       # Starting capital
    leverage = Column(Float, default=2.0)         # Fixed leverage
    min_price = Column(Float, default=5.0)        # Minimum stock price
    min_atr = Column(Float, default=0.50)         # Minimum ATR
    min_avg_volume = Column(Float, default=1000000.0)  # Minimum avg volume
    
    # Execution stats
    total_days = Column(Integer, default=0)
    days_processed = Column(Integer, default=0)
    status = Column(String(20), default="pending")  # pending, running, completed, failed
    
    # Performance summary (computed after completion)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    no_entry_trades = Column(Integer, default=0)
    total_pnl_pct = Column(Float, default=0.0)
    total_pnl_dollars = Column(Float, default=0.0)
    win_rate = Column(Float, default=0.0)
    max_drawdown_pct = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)


class DailyPerformance(Base):
    """
    Aggregated daily P&L for fast analytics queries.
    
    Pre-computed from simulated_trades to avoid expensive aggregations.
    """
    __tablename__ = "daily_performance"
    
    id = Column(Integer, primary_key=True, index=True)
    backtest_run_id = Column(Integer, nullable=True, index=True)  # NULL = production/default
    date = Column(DateTime, nullable=False, index=True)
    
    # Trade counts
    total_trades = Column(Integer, default=0)
    trades_entered = Column(Integer, default=0)
    winners = Column(Integer, default=0)
    losers = Column(Integer, default=0)
    
    # P&L
    total_pnl_pct = Column(Float, default=0.0)
    total_pnl_dollars = Column(Float, default=0.0)  # At 1x leverage
    total_pnl_leveraged = Column(Float, default=0.0)  # At actual leverage
    
    # Best/worst trades
    best_trade_pnl = Column(Float, default=0.0)
    best_trade_ticker = Column(String(10), nullable=True)
    worst_trade_pnl = Column(Float, default=0.0)
    worst_trade_ticker = Column(String(10), nullable=True)
    
    # Running totals (for equity curve)
    cumulative_pnl = Column(Float, default=0.0)
    equity = Column(Float, default=1000.0)  # Starting capital + cumulative P&L
    drawdown_pct = Column(Float, default=0.0)  # Current drawdown from peak
    
    __table_args__ = (
        UniqueConstraint('backtest_run_id', 'date', name='uix_dailyperf_run_date'),
    )
